# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks

# Setup
title:            Vandana Tomar
tagline:          'Welcome'
description:      'If you can't follow the rules, break them'
url:              http://vandana162.github.io

author:
  name:           'Vandana Tomar'
  url:             vandana162.github.io
  email:          'anejaalisha37@gmail.com'
  github:         'https://github.com/vandana162'
  twitter:        'https://twitter.com/alisha_aneja17'
  linkedin:       'https://www.linkedin.com/in/alisha-aneja-509252128/'

  rss:            'https://alisha17.github.io/feed.xml'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/vandana162

gems:             [jekyll-gist, jekyll-paginate, jekyll-archives]

defaults:
  - scope:
      path: "assets"
    values:
      image: true

plugins_dir:
  - jekyll-feed
